# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rubycue"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blake Smith"]
  s.date = "2012-07-23"
  s.description = "Basic ruby parser for song cuesheets"
  s.email = "blakesmith0@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rubycue.rb",
    "lib/rubycue/cuesheet.rb",
    "lib/rubycue/exceptions.rb",
    "lib/rubycue/index.rb",
    "rubycue.gemspec",
    "spec/fixtures/malformed.cue",
    "spec/fixtures/multi_file.cue",
    "spec/fixtures/test.cue",
    "spec/spec_helper.rb",
    "spec/unit/cuesheet_spec.rb",
    "spec/unit/index_spec.rb"
  ]
  s.homepage = "http://github.com/blakesmith/rubycue"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Ruby cuesheet track parser"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

