# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubycue}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blake Smith"]
  s.date = %q{2010-10-26}
  s.description = %q{Basic ruby parser for song cuesheets}
  s.email = %q{blakesmith0@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rubycue.rb",
     "lib/rubycue/cuesheet.rb",
     "lib/rubycue/exceptions.rb",
     "lib/rubycue/index.rb",
     "spec/fixtures/malformed.cue",
     "spec/fixtures/test.cue",
     "spec/spec_helper.rb",
     "spec/unit/cuesheet_spec.rb",
     "spec/unit/index_spec.rb"
  ]
  s.homepage = %q{http://github.com/blakesmith/rubycue}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby cuesheet track parser}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/unit/cuesheet_spec.rb",
     "spec/unit/index_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

